language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: pNbutCKct1dXz9dOuqAXeuP5QeUCgWMZlmyK/dLj5tSYm/E3KBfYRQXQr2ozm/fOc4sstJvLo8qr0+Yk9e53Edu9n5VD2vZXkG08cv2bW5typZyRf9FoXYPEG4CY4xsD0qFeyYDeyR7J6C4NIxasNJ5dGlZzQ3pkN98cxaLcLjgQP+OVUg0y6qqZTXRU+V0IuTMT8UYXi26gRmfHn236A0apaFyZhlFxAkcEKLy8sth1KYlu92KqXmkRfsg3BXgsuSJyq0DPTaBfiE8NxrBVevJcs06ieWAeIe1V53hifoTh3rrlNCqbzOUk0vpalnpZv+GPwt6IywTS0S3v2rmItIOsq9RHSyiKiIGV2CO326HrD3ZJu9AElLh1NQXVmRKpT3s8rfw/3WSHx5VK8rmwJW3a0bV5m98vmXdwL0EUTnrNR62KEAdY96D32gY1Nr/G6u8rULRspwJ4clJF/Ni754SDdOf3rsK0A4b9lLnTE91bvVDBjOGhEppKWOwcnmY7bqbSTTZ6Lk8qkurefL8EE4WaHC3Dovd6gPExS3o0sy+9RUZInBCNfuw9uQJwBULKMc/EaPizm2Xxb+GyzcUncvO6XV5uN+VralPTmgFm76xrN6OiyRmpQnN97NnaDYUjWatgYfAFr3nyBm9pfKrEIFb9VjCl+GU7qxNAyGxFq0Y=
  app: sample-home-task-2
